- name: add roboshop user
  ansible.builtin.user:
    name: roboshop

- name: remove default content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directoy
  ansible.builtin.file:
    path: /app
    state: directory

- name: download and unzip the app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes